services:
    aerospike:
        image: aerospike:ce-7.2.0.1_2
        ports:
            - "3000-3002:3000-3002"
        volumes:
            - .:/var/www/balance
            - ./docker/aerospike:/etc/aerospike
        environment:
            NAMESPACE: cache

    aerospike-gateway:
        build: ./aerospike-rest-gateway
        ports:
            - "8080:8080"
        environment:
            - aerospike_restclient_hostname=aerospike

    postgres:
        build: ./docker/postgres
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready --dbname=loms --username=loms" ]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: balance
            POSTGRES_PASSWORD: balance
            POSTGRES_DB: balance

    php-fpm:
        build: ./docker/php
        volumes:
            - .:/var/www/balance
        working_dir: /var/www/balance
        depends_on:
            - composer

    nginx:
        image: nginx:1.27.2-alpine3.20
        volumes:
            - .:/var/www/balance
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - postgres
            - php-fpm
            - aerospike
            - aerospike-gateway

    migrations:
        build: ./docker/php
        command: php artisan migrate
        volumes:
            - .:/var/www/balance
        working_dir: /var/www/balance
        depends_on:
            postgres:
                condition: service_healthy

    composer:
        build: ./docker/php
        command: composer install
        volumes:
            - .:/var/www/balance
        working_dir: /var/www/balance
        depends_on:
            - postgres

    phpunit:
        build: ./docker/php
        command: vendor/bin/phpunit --coverage-html=storage/coverage
        working_dir: /var/www/balance
        env_file:
            - ./docker/php/env/testing.env
        volumes:
            - .:/var/www/balance
        links:
            - composer
